# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
import torch

# Create random tensor
randTensor = torch.rand(7,7)
randTensor, randTensor.size()

(tensor([[0.1907, 0.9220, 0.7840, 0.8896, 0.7467, 0.3003, 0.8864],
         [0.9942, 0.8080, 0.9162, 0.1646, 0.7891, 0.6432, 0.6844],
         [0.7423, 0.5087, 0.1830, 0.3693, 0.1198, 0.2370, 0.8128],
         [0.4434, 0.2171, 0.5045, 0.3331, 0.4012, 0.1375, 0.1154],
         [0.4672, 0.4682, 0.2715, 0.9873, 0.1628, 0.8283, 0.4279],
         [0.5912, 0.8332, 0.2546, 0.1513, 0.5993, 0.8792, 0.4142],
         [0.5260, 0.0996, 0.0221, 0.8088, 0.8950, 0.2827, 0.3824]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
# Create another random tensor
randTensor2 = torch.rand(1,7)
print(f"Tensor 1= {randTensor2}")

#transpose the tensor
trans = randTensor2.T
# Perform matrix multiplication

mul = randTensor.matmul(trans)
print(f"Mulplied result: {mul}")

Tensor 1= tensor([[0.2883, 0.7656, 0.7200, 0.1415, 0.7765, 0.0248, 0.0223]])
Mulplied result: tensor([[2.0582],
        [2.2320],
        [0.9045],
        [1.0219],
        [0.9848],
        [1.5094],
        [1.0688]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed
seed = torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7,7)
seed = torch.manual_seed(0)
tensor2 = torch.rand(1,7)
transpose_tensor2 = tensor2.T
# Matrix multiply tensors
tensor_multiply = tensor1.matmul(transpose_tensor2)
print(tensor_multiply)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [2]:
import torch
# Set random seed on the GPU
seed = torch.cuda.manual_seed(1234)
print(seed)

None



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [22]:

import torch
# Access to GPU - Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

# Set random seed
seed= 1234

# Create two random tensors on GPU
seed = torch.cuda.manual_seed(seed)
tensor1 = torch.rand(2,3, device= 'cuda')
seed = torch.cuda.manual_seed(1234)
tensor2 = torch.rand(2,3,device='cuda')



print(tensor1, tensor2)

cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [24]:
# Perform matmul on tensor_A and tensor_B
multiplied = tensor1.matmul(tensor2.T)
print(multiplied, multiplied.size())

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [25]:
# Find max
max = multiplied.max()
# Find min
min = multiplied.min()
print(max,min)

tensor(1.4578, device='cuda:0') tensor(0.8358, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [26]:
# Find arg max
print(max.argmax())

# Find arg min
print(min.argmin())


tensor(0, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [30]:
# Set seed


# Create random tensor
seed = torch.cuda.manual_seed(7)
tensor1 = torch.rand(1,1,1,10, device= 'cuda')
print(tensor1, tensor1.size())
# Remove single dimensions

x = tensor1[0,0,0,:]
# Print out tensors and their shapes
print(x)

tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
           0.6333, 0.5733]]]], device='cuda:0') torch.Size([1, 1, 1, 10])
tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
        0.5733], device='cuda:0')
